# Streamlit Secrets Configuration Template
# Copy this file to .streamlit/secrets.toml and fill in your values

# OpenAI Configuration
OPENAI_API_KEY = "sk-your-openai-api-key-here"

# Optional: Advanced AI Settings
OPENAI_MODEL = "gpt-4o-mini"
OPENAI_MAX_TOKENS = 1000
OPENAI_TEMPERATURE = 0.1

# App Configuration
APP_TITLE = "IFC Smart Query System"
DEFAULT_LANGUAGE = "hebrew"

# Analytics (Optional)
ANALYTICS_ENABLED = true
LOG_QUERIES = true

# Database Settings
DEFAULT_DB_PATH = "sample_project.duckdb"

# UI Settings
SHOW_DEBUG_INFO = false
ENABLE_DEVELOPER_MODE = false